# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergame',
            name='stage',
        ),
        migrations.AddField(
            model_name='playergame',
            name='state',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
