# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0002_auto_20160105_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergame',
            name='state',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
