# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
