# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0006_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ref',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
